### ISSUE TITLE
ValueError: I/O operation on closed file while reading the file content for sending emails

### ISSUE THREAD

**Issue by nicksce** [torchbox/wagtail-storages#23]
It gives the above-mentioned error when tried to read the file content for sending it via email attachment.

The code works absolutely fine when the backend storage is the local file storage instead of AWS.

```python
        for field in form.files:
            for file in form.files.getlist(field):
                file.seek(0)
                email.attach(file.name, file.read(), file.content_type)

        # finally send the email
        email.send(fail_silently=True)
```

**Comment by tm-kn** [comment]
Thanks for the report.

I don't think this is enough information to understand this issue.

1. What's `form.files`? Can you share all the relevant code?
2. Do you get the same issue with just vanilla https://github.com/jschneier/django-storages?

**Comment by nicksce** [comment]
Thanks for your immediate response @tm-kn 

Yes I get the same issue with the vanilla django-storage.

I am using streamforms.

```python
@register('process_form_submission')
def email_submission(instance, form):
     # Some code for email decoration.
        for field in form.files:
            for file in form.files.getlist(field):
                file.seek(0)
                email.attach(file.name, file.read(), file.content_type)

        # finally send the email
        email.send(fail_silently=True)
```

Hope this inforamation would help you.

**Comment by tm-kn** [comment]
This has nothing to do with this package. I'm sorry. This may be just a code issue where you need to re-open the file from the storage. You are probably better off trying to re-open the file somehow before reading it or seeking help on https://github.com/labd/wagtailstreamforms/issues.
