### ISSUE TITLE
Make release of version 0.5.1

### ISSUE THREAD

**Issue by PetrDlouhy** [torchbox/wagtail-storages#30]
The `wagtail-storages` has version `0.5.1rc1` and `0.5rc1` on PyPI for several months now.
There is no production version that supports Django 4.0 nor Wagtail 3.0 yet.

What is blocking new production release?

**Comment by tm-kn** [comment]
Thanks for the nudge - just been released.

**Comment by PetrDlouhy** [comment]
@tm-kn Thank you very much.
