### ISSUE TITLE
Wagtail 4.0 support

### ISSUE THREAD

**Issue by engineervix** [torchbox/wagtail-storages#32]
With the [recent release of wagtail 4.0](https://docs.wagtail.org/en/latest/releases/4.0.html), this package needs updating to support the new version, as it currently only supports Wagtail < 4.0:

https://github.com/torchbox/wagtail-storages/blob/8b724535b02c0a823841530f74f35b73aea336f5/setup.cfg#L34

Happy to create a PR for this. I've made initial changes on a fork, and the test suite passes

https://github.com/engineervix/wagtail-storages/commit/429c7b6d03ca6ec95015acb37f5f3f1979f46e08

**Comment by tm-kn** [comment]
Thanks a lot! Please create a PR.

**Comment by PetrDlouhy** [comment]
@engineervix Would you please create the PR?

**Comment by engineervix** [comment]
Looks like @nickmoreton beat me to it! See #33
